export const ART_DIR = "/harbor/processed";

export const BOOT_IMAGES = [
  "water",
  "water-deep",
  "waves-foam",
  "waves-0",
  "wharf-planks",
  "road-stone",
  "player-idle",
  "player-idle-stand",
  "player-walk-0",
  "player-walk-1",
  "player-walk-2",
  "player-walk-3",
  "player-walk-pass",
  "player-use",
  "coffee-shop",
  "lighthouse",
  "far-shore",
  "far-cottage-a",
  "far-cottage-b",
  "prudence-ferry",
  "seawall",
  "dock",
  "fender",
  "cormorant-perch",
  "cormorant-wings",
  "cormorant-idle",
  "boat",
  "wake",
  "shack-a",
  "shack-b",
  "sign-github",
  "sign-x",
  "kayak",
  "cloud",
  "sun",
  "moon",
  "star",
  "glow-window",
  "glow-street",
  "lantern",
  "lantern-glow",
  "flagpole",
  "flag-limp-0",
  "flag-limp-1",
  "flag-limp-2",
  "flag-half-0",
  "flag-half-1",
  "flag-half-2",
  "flag-full-0",
  "flag-full-1",
  "flag-full-2",
  "postcard-harbor",
  "postcard-stamp",
] as const;

export const STREAM_IMAGES = [
  "seawall-stairs",
  "boat-underway",
  "paddle",
  "trap",
  "trap-stack",
  "trap-buoy",
  "shark-fin",
  "waves-1",
  "waves-2",
] as const;

export function artUrl(key: string): string {
  return `${ART_DIR}/${key}.png`;
}
